// Offline regression checks: node tests/test_frontend.cjs
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const elements = new Map();
function element(id) {
  if (!elements.has(id)) elements.set(id,{value:'',innerHTML:'',textContent:'',hidden:false,disabled:false,dataset:{},classList:{toggle(){}},setAttribute(){},querySelectorAll(){return []},querySelector(){return {insertAdjacentHTML(){}}},insertAdjacentHTML(){},focus(){},close(){},showModal(){}});
  return elements.get(id);
}
const ctx = vm.createContext({console,Date,URL,encodeURIComponent,document:{getElementById:element,querySelector:()=>({content:'test-csrf',focus(){}}),querySelectorAll:()=>[]},window:{scrollY:123,scrollTo(){},matchMedia:()=>({matches:false})},location:{pathname:'/',hash:''},history:{pushState(){}},setInterval(){}});
const source=fs.readFileSync('static/js/app.js','utf8').split('document.addEventListener("click"')[0];
vm.runInContext(fs.readFileSync('static/js/i18n.js','utf8'),ctx);
vm.runInContext(source,ctx);
const run=code=>vm.runInContext(code,ctx);
run('language="en"');
assert.equal(run('html`<h2>Profil pemain</h2><span>${"Profil pemain"}</span>`'),'<h2>Player profile</h2><span>Profil pemain</span>');
assert.equal(run('t("Simpan preferensi")'),'Save preferences');
assert.equal(run('t("Rankings pages")'),'Rankings pages');
run('language="id"');
const storage=new Map();
ctx.localStorage={getItem:key=>storage.get(key) ?? null,setItem:(key,value)=>storage.set(key,value),removeItem:key=>storage.delete(key)};
run('rememberAccount({uid:"812345678",nickname:"<Player>"});rememberAccount({uid:"812345678",nickname:"Updated"});');
assert.equal(run('readAccounts().length'),1);
assert.ok(element('recent-accounts').innerHTML.includes('Updated'));
storage.set('hoyo-public-accounts','broken JSON');
assert.equal(run('readAccounts().length'),0);
storage.clear();
run(`state.explore={uid:"812345678",groups:[{id:"1",progress:0},{id:"2",progress:100},{id:"3",progress:null}]};`);
assert.equal(run('explorationTotal(state.explore,new Set(["1","2","3"]))'),50);
assert.equal(run('explorationTotal(state.explore,new Set())'),null);
storage.set('hoyo-explore-regions:812345678','["2","unknown"]');
assert.equal(run('exploreSelection(state.explore).size'),1);
assert.equal(run('exploreSelection({...state.explore,uid:"823456789"}).size'),3);
run(`state.explore={uid:"812345678",nickname:"Fixture",server:"os_asia",groups:[{id:"1",progress:70}],regions:[{id:"1",group_id:"1",name:"Mondstadt",progress:80,special:false,tribes:[],offerings:[],areas:[]},{id:"21",group_id:"1",group_name:"Mondstadt",name:"Windrest Peak",progress:60,special:true,tribes:[],offerings:[],areas:[]}]};state.exploreSelected=new Set(["1"]);state.exploreResult={meta:{fetched_at:new Date().toISOString()}};renderExplore();`);
assert.ok(element('explore').innerHTML.indexOf('id="explore-total"')<element('explore').innerHTML.indexOf('class="explore-grid"'));
assert.equal((element('explore').innerHTML.match(/data-explore-region="1"/g)||[]).length,2);
assert.ok(!element('explore').innerHTML.includes('<span>Hitung di total</span>'));
storage.clear();
run(`state.config={public_account:{uid:""},akasha:{enabled:false},hoyolab:{enabled:false}};`);
assert.equal(run('number(null)'),'Belum tersedia');
assert.equal(run('number(0)'),'0');
assert.equal(run('number(.001)'),'0,001');
assert.equal(run('topPercent(.000001)'),'<0,0001%');
assert.equal(run('rankValue(null)'),'Belum tersedia');
assert.equal(run('escape("<img onerror=alert(1)>")'),'&lt;img onerror=alert(1)&gt;');
run(`state.rankings=[{character:"Null",rank:null},{character:"Zero",rank:0},{character:"High",rank:9}];state.rankDir=1;renderRankings();`);
let html=element('rankings').innerHTML;
assert.ok(html.indexOf('Zero')<html.indexOf('High') && html.indexOf('High')<html.indexOf('Null'));
run(`state.rankDir=-1;renderRankings();`);
html=element('rankings').innerHTML;
assert.ok(html.indexOf('High')<html.indexOf('Zero') && html.indexOf('Zero')<html.indexOf('Null'));
run(`state.rankings=[{character:"Akasha fixture",element:"Pyro",build_hash:"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",build_snapshot:{id:1},rank:1}];renderRankings();`);
html=element('rankings').innerHTML;
assert.ok(html.includes('data-akasha-build="0"') && html.includes('See Detail ↗'));
assert.ok(html.includes('https://akasha.cv/profile/') && html.includes('Akasha ↗'));
run(`state.rankings[0].build_snapshot=null;renderRankings();`);
assert.ok(!element('rankings').innerHTML.includes('data-akasha-build='));
const progressFrames=[];
let progressValue=80;
const progressBar={getAttribute(name){return name==='aria-label'?'Total':String(progressValue)},getBoundingClientRect(){return {width:100}},firstElementChild:{style:{},getBoundingClientRect(){return {width:20}},animate(frames,options){progressFrames.push({frames,options})}}};
ctx.document.querySelectorAll=()=>[progressBar];
ctx.window.matchMedia=()=>({matches:false});
run('animateExploreProgress(new Map([["Total",.2]]))');
assert.deepEqual(Array.from(progressFrames[0].frames,f=>f.transform),['scaleX(0.2)','scaleX(0.8)']);
assert.equal(progressFrames[0].options.duration,480);
progressValue=20;
run('animateExploreProgress(new Map([["Total",.8]]))');
assert.deepEqual(Array.from(progressFrames[1].frames,f=>f.transform),['scaleX(0.8)','scaleX(0.2)']);
ctx.window.matchMedia=()=>({matches:true});
run('animateExploreProgress(new Map([["Total",.8]]))');
assert.equal(progressFrames.length,2);
progressValue=81.9;
run('animateExploreProgress(new Map())');
assert.equal(progressBar.firstElementChild.style.transform,'scaleX(0.8190000000000001)');
assert.ok(!run('exploreProgress(81.9,"Total")').includes('style='));
ctx.document.querySelectorAll=()=>[];
const character={id:1,name:'Test',element:'Pyro',level:90,constellation:0,stats:[{label:'Max HP',value:100},{label:'Elemental Mastery',value:0}],talents:{101:9},artifacts:[],weapon:null};
ctx.fixture=character;
run('state.characters=[fixture];state.charPage=5;renderCharacters();');
assert.equal(run('state.charPage'),1);
run('detail(1);');
assert.equal(run('state.view'),'detail');
assert.equal(element('character-detail').hidden,false);
assert.ok(element('character-detail').innerHTML.includes('Max HP'));
run('returnToShowcase();');
assert.equal(run('state.view'),'showcase');
assert.equal(run('compactSets(["Emblem (4pc)","Other (1pc)"])'),'Emblem (4pc)');
assert.equal(run('compactSets(["A (2pc)","B (2pc)","C (1pc)"])'),'A (2pc) + B (2pc)');

async function races() {
  const waiting=new Map();
  ctx.fetch=(url)=>new Promise(resolve=>waiting.set(url,resolve));
  element('uid').value='812345671';
  const a=run('loadPublic()');
  element('uid').value='812345672';
  const b=run('loadPublic()');
  const response=uid=>({ok:true,json:async()=>({data:{profile:{uid,nickname:uid},characters:[character]},meta:{fetched_at:new Date().toISOString(),refresh_after_seconds:0}})});
  waiting.get('/api/v1/showcase/812345672')(response('812345672'));
  await new Promise(resolve=>setImmediate(resolve));
  waiting.get('/api/v1/status')({ok:true,json:async()=>({data:{sources:{}}})});
  await b;
  waiting.get('/api/v1/showcase/812345671')(response('812345671'));
  await a;
  assert.equal(run('state.loadedUid'),'812345672');
  assert.ok(!element('profile').innerHTML.includes('812345671'));
  run('rememberCooldown("showcase:812345672",20);updateLoadButton();');
  assert.equal(element('load-account').disabled,true);
  const notesResponses=[];
  ctx.fetch=url=>url.endsWith('/status') ? Promise.resolve({ok:true,json:async()=>({data:{sources:{}}})}) : new Promise(resolve=>notesResponses.push(resolve));
  run('state.config.hoyolab={enabled:true,game_uid:"899999991"};');
  const privateA=run('loadNotes()');
  run('state.config.hoyolab.game_uid="899999992";state.notesGeneration++;');
  element('notes').innerHTML='Waiting for private B';
  notesResponses[0]({ok:true,json:async()=>({data:{uid:'899999991',nickname:'private A'},meta:{source:'hoyolab',fetched_at:new Date().toISOString()}})});
  await privateA;
  assert.equal(element('notes').innerHTML,'Waiting for private B');
  assert.equal(notesResponses.length,2); // A's completion starts a request for the new account.
  const exploreResponses=[];
  ctx.fetch=()=>new Promise(resolve=>exploreResponses.push(resolve));
  run('state.view="explore";state.config.hoyolab={enabled:true,game_uid:"899999991"};state.exploreGeneration=1;state.explore=null;');
  const exploreA=run('loadExplore()');
  run('state.config.hoyolab.game_uid="899999992";state.exploreGeneration++;');
  element('explore').innerHTML='Waiting for B';
  exploreResponses[0]({ok:true,json:async()=>({data:{uid:'899999991',regions:[],groups:[]}})});
  await exploreA;
  assert.equal(run('state.explore'),null);
  assert.equal(exploreResponses.length,2);
  exploreResponses[1]({ok:true,json:async()=>({data:{uid:'899999992',regions:[],groups:[]}})});
  await new Promise(resolve=>setImmediate(resolve));
  assert.equal(run('state.explore.uid'),'899999992');
  console.log('Frontend checks passed: null/zero, precision, escaping, sorting, pagination, detail, UID race, private account race, cooldown.');
}
races().catch(e=>{console.error(e);process.exitCode=1});
